[package]

name = "pop3"
version = "0.0.4"
authors = ["Matt McCoy <mattnenterprise@yahoo.com>"]
repository = "https://github.com/mattnenterprise/rust-pop3"
description = "POP3 client for Rust"
readme = "README.md"
license = "MIT"

[lib]
name = "pop3"
path = "src/pop3.rs"

[[bin]]
name = "example"
path = "example.rs"

[dependencies]
openssl = "0.6.0"
regex = "0.1.28"
